version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlenv
    privileged: true
    command: /sbin/init
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /data:/data
      - ~/.ssh/docker_rsa.pub:/root/.ssh/authorized_keys
      - workdir:/root/workdir
    working_dir: /root
    ports:
      - '2222:22'
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  workdir:
    driver: local
