services:
  app:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}

    image: mlenv-app:1.0.0
    container_name: mlenv-app-${USERNAME}
    user: user
    hostname: docker
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: ./dev
        target: /home/user/dev

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  data:
  dev:
