services:
  app:
    image: mlenv-app:latest
    container_name: mlenv
    hostname: docker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /data:/data
      - ./dev:/root/dev
    working_dir: /root/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

volumes:
  workdir:
    driver: local
