services:
  app:
    image: mlenv-app:latest
    container_name: mlenv
    hostname: docker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - type: bind
        source: /data
        target: /data
      - type: bind
        source: ./dev
        target: /root/dev
    working_dir: /root/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

