services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlenv
    hostname: docker
    ports:
      - '2222:22'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /data:/data
      - ~/.ssh/docker_rsa.pub:/root/.ssh/authorized_keys
      - ./dev:/root/dev
    working_dir: /root/dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

volumes:
  workdir:
    driver: local
